In [92]:
import pandas as pd
import numpy as np
from rake_nltk import Rake
from nltk.sentiment import SentimentIntensityAnalyzer

In [93]:
import nltk 
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nickt\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [94]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\nickt\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [95]:
r = Rake()
sentiment_analyzer = SentimentIntensityAnalyzer()

In [96]:
df = pd.read_excel('C:\\Users\\nickt\\Desktop\\Διπλωματική\\Εργασία\\Δεδομένα\\Top5Attractions.xlsx')

In [97]:
df

,id,Language,Location_id,Published_Date,Rating,Text,Title,Travel_Date,User_Reviews,User_Location
0,120069680,en,243212,2011-11-02 06:29:23,5,great temple with 6th century mosaics and a sm...,great.. simply great,2011-10-01,22.0,Greece
1,120192863,it,243212,2011-11-05 04:48:46,5,E' una chiesa veramente splendida: le sue dime...,Chiesa di San Demetrio,2011-11-01,52.0,Italy
2,122213311,en,243212,2011-12-28 23:13:51,5,"this is a very old church, you can see the old...",very old church with great history,NaT,18.0,Greece
3,122322146,it,243212,2011-12-31 05:35:28,4,"E posizionata in alto rispetto alla citta, ver...",Visita chiesa piu importante,2011-12-01,17.0,Italy
4,123793581,en,243212,2012-01-29 09:36:47,5,A very old and important byzantine church. The...,Traditional church,2012-01-01,8.0,Greece
...,...,...,...,...,...,...,...,...,...,...
12306,340408202,el,2462221,2016-01-16 03:13:35,5,Η ωραιοτερη πλατεια της Ελλαδος που μονο Ιταλ...,La piazza piu bella,2016-01-01,50.0,NaN
12307,339510140,el,2462221,2016-01-12 15:36:52,5,Είμαι βολιώτης και έρχομαι αρκετά συχνά λόγο τ...,Η ζωή μου,2016-01-01,39.0,NaN
12308,339055602,el,2462221,2016-01-10 21:07:14,3,το Σαββατοκύριακο 19-20 Δεκεμβρίου 2015 αποφασ...,Η πανέμορφη πλατεία Αριστοτέλους σαν τσίρκο!!!,2015-12-01,80.0,Greece
12309,338859004,el,2462221,2016-01-10 02:56:33,5,"Χρονια ολάκερα, σημείο ανάρτηση αναφοράς για τ...",Σημείο αναφοράς..,2015-02-01,191.0,Greece
12310,338725499,el,2462221,2016-01-09 10:19:03,5,"Εξαιρετικής αισθητικής ,ενώνει το παραλιακό μέ...",Mοναδικη!!!,2015-02-01,3.0,Germany

In [98]:
df = df.loc[df['Language']=='en']
df

,id,Language,Location_id,Published_Date,Rating,Text,Title,Travel_Date,User_Reviews,User_Location
0,120069680,en,243212,2011-11-02 06:29:23,5,great temple with 6th century mosaics and a sm...,great.. simply great,2011-10-01,22.0,Greece
2,122213311,en,243212,2011-12-28 23:13:51,5,"this is a very old church, you can see the old...",very old church with great history,NaT,18.0,Greece
4,123793581,en,243212,2012-01-29 09:36:47,5,A very old and important byzantine church. The...,Traditional church,2012-01-01,8.0,Greece
5,123968169,en,243212,2012-02-01 06:04:58,5,The history of this church and the area where ...,All layers of Greece's history in one building,NaT,18.0,Greece
6,124072868,en,243212,2012-02-03 08:56:09,3,We just went to light a cuddle and see the fam...,Boring,2012-01-01,6.0,Cyprus
...,...,...,...,...,...,...,...,...,...,...
12212,514122361,en,2462221,2017-08-16 23:48:27,5,Beautiful square with maUnited States activiti...,Beautiful square with maUnited States activiti...,2017-07-01,12.0,Greece
12213,512862635,en,2462221,2017-08-14 13:01:52,4,"Nice central square, nice architecture surroun...",Nice central square,2017-08-01,142.0,Estonia
12214,512314426,en,2462221,2017-08-13 11:04:57,5,A huge square surrounded by impressive buildin...,Comes alive at night,2017-08-01,132.0,Australia
12215,510611987,en,2462221,2017-08-09 09:12:33,5,You can not miss it. It is right on the coast ...,Center of town,2017-07-01,28.0,NaN
12216,510094530,en,2462221,2017-08-08 09:30:11,5,Great view to the sea and nice places to sit a...,Nice place full of coffee shops and small shop...,2017-07-01,57.0,Cyprus

In [99]:
def extract_keyword(review):
    r.extract_keywords_from_text(str(review))
    phrases_with_scores = r.get_ranked_phrases_with_scores()
    if phrases_with_scores:
        no1_phrase = phrases_with_scores[0][1]
        words = nltk.word_tokenize(no1_phrase)
        return words[0]
    else:
        return ''
#Αυτή η συνάρτηση εξάγει μια λέξη-κλειδί που περιγράφει καλύτερα το συναίσθημα της κριτικής

In [100]:
def sentiment(review):
    sentiment_score = sentiment_analyzer.polarity_scores(str(review))['compound']
    sentiment_score = sentiment_analyzer.polarity_scores(str(review))['compound']
    if sentiment_score>0.2:
        sentiment='Positive'
    elif sentiment_score <-0.2:
        sentiment='Negative'
    else:
        sentiment='Neutral'
    return sentiment
#Αυτή η συνάρτηση ταξινομεί το συναίσθημα του κειμένου σε "Θετικό", "Ουδέτερο" και "Αρνητικό" με βάση τις βαθμολογίες 
#μεταξύ -1 προς 1.

In [101]:
df['Sentiment'] = df['Title'].apply(sentiment)

C:\Users\nickt\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [102]:
df['Keyword'] = df['Title'].apply(extract_keyword)

C:\Users\nickt\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [107]:
df.to_excel('English_Reviews.xlsx')